# Generated by Django 6.0.1 on 2026-01-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
    ]
